---
title: "final_hybrid_ms_code"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
date: "2024-07-13"
---

```{r Libraries}


#Here we're loading the appropriate libraries into the session.

library(car)
library(ggplot2)
library(ggpubr)
library(lmerTest)
library(AICcmodavg)
library(systemfonts)
library(xtable)
library(ggtext)
library(knitr)
library(grateful)
library(kableExtra)




theme_set(theme_classic())

```

```{r Data}


#Here we're importing the dataset, defining variables, and creating subsets of data.
dat <- read.csv("C:/Users/18034/Dropbox/Research/hybrid_behavior/hybrid_data.csv")

dat$id <- as.factor(dat$id)
dat$bout <- as.factor(dat$bout)
dat$pop <- as.factor(dat$pop)
dat$temp <- as.factor(dat$temp)
dat$group <- as.factor(dat$group)
dat$opppop <- as.factor(dat$opppop)
dat$TAI <- as.numeric(dat$TAI)
dat$TEI <- as.numeric(dat$TEI)
dat$initiated <- factor(dat$initiated, levels=c("1","0"))


pshe <- dat[which(dat$pop=="pshe"),]
ptey <- dat[which(dat$pop=="ptey"),]
pshetey <- dat[which(dat$pop=="pshetey"),]
parents <- dat[which(dat$pop=="pshe" | dat$pop=="ptey"),]
fifteen <- dat[which(dat$temp=="15"),]
twothree <- dat[which(dat$temp=="23"),]


```

```{r How does performance vary across taxa?}

##Thermal sensitivity aside, are there differences in aggression or evasion between taxa?

aggdiff15<- lmer(log(TAI+1) ~ pop+(1|id)+(1|bout), data=fifteen)
Anova(aggdiff15)
#no
aggdiff23 <- lmer(log(TAI+1) ~ pop+(1|id)+(1|bout), data=twothree)
Anova(aggdiff23)
#no

evdiff15 <- lmer(log(TEI+1 )~ pop+(1|id)+(1|bout), data=fifteen)
Anova(evdiff15)
#no
evdiff23 <- lmer(log(TEI+1) ~ pop+(1|id)+(1|bout), data=twothree)
Anova(evdiff23)
#no


```

```{r How does temperature affect the frequency at which individuals initiate bouts?}

#Does frequency of initiation change with temperature?
#We are comparing populations separately usiing chi-square tests.

pshe.bold <- chisq.test(table(pshe$temp, pshe$initiated))
pshe.bold
table(pshe$temp, pshe$initiated)
#No

ptey.bold <- chisq.test(table(ptey$temp, ptey$initiated))
ptey.bold
#No

pshetey.bold <- chisq.test(table(pshetey$temp, pshetey$initiated))
pshetey.bold
table(pshetey$temp, pshetey$initiated)
#No

```

```{r How is temperature related to performance in all individuals?}

###These are our full sample models exploring how hybrid status ("group") is related to thermal sensitivity.

#Here we're building our models and assigning them names, specifically for aggressive behavior (TAI).

candidate_all_TAI <- list()
  candidate_all_TAI[[1]] <- lmer(log(TAI+1)~temp+group+temp*group+mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[2]] <- lmer(log(TAI+1)~group+mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[3]] <- lmer(log(TAI+1)~temp+mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[4]] <- lmer(log(TAI+1)~temp+group+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[5]] <- lmer(log(TAI+1)~temp+group+mass.diff+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[6]] <- lmer(log(TAI+1)~temp+group+bout+temp*group+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[7]] <- lmer(log(TAI+1)~temp+group+mass.diff+temp*group+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[8]] <- lmer(log(TAI+1)~group+mass.diff+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[9]] <- lmer(log(TAI+1)~group+temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[10]] <- lmer(log(TAI+1)~group+temp+group*temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[11]] <- lmer(log(TAI+1)~group+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[12]] <- lmer(log(TAI+1)~mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[13]] <- lmer(log(TAI+1)~mass.diff+temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[14]] <- lmer(log(TAI+1)~temp+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[15]] <- lmer(log(TAI+1)~temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[16]] <- lmer(log(TAI+1)~group+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[17]] <- lmer(log(TAI+1)~mass.diff+(1|id), data=dat, na.action='na.fail',REML = FALSE) 
  candidate_all_TAI[[18]] <- lmer(log(TAI+1)~bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TAI[[19]] <- lmer(log(TAI+1)~1+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  
candidate_all_TAI_names <- c("Global","Group+Mass+Bout","Temp+Mass+Bout","Temp+Group+Bout","Temp+Group+Mass","Temp+Group+Bout+TempxGroup","Temp+Group+Mass+TempxGroup","Group+Mass","Group+Temp","Group+Temp+TempxGroup","Group+Bout","Mass+Bout","Mass+Temp","Bout+Temp","Temp","Group","Mass","Bout","Null")

#Here, we're comparing models.

all_tai_aic <- aictab(candidate_all_TAI,candidate_all_TAI_names)
all_tai_aic

#Here, we're averaging models and summarizing the temperature-only model, which had a sufficiently low Delta_AICC.

modavg(candidate_all_TAI,parm='temp23',candidate_all_TAI_names,exclude=list("TempxGroup"))
summary(candidate_all_TAI[[15]])



###Here, we're repeating the analysis for evasive behavior.

candidate_all_TEI <- list()
  candidate_all_TEI[[1]] <- lmer(log(TEI+1)~temp+group+temp*group+mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[2]] <- lmer(log(TEI+1)~group+mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[3]] <- lmer(log(TEI+1)~temp+mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[4]] <- lmer(log(TEI+1)~temp+group+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[5]] <- lmer(log(TEI+1)~temp+group+mass.diff+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[6]] <- lmer(log(TEI+1)~temp+group+bout+temp*group+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[7]] <- lmer(log(TEI+1)~temp+group+mass.diff+temp*group+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[8]] <- lmer(log(TEI+1)~group+mass.diff+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[9]] <- lmer(log(TEI+1)~group+temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[10]] <- lmer(log(TEI+1)~group+temp+group*temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[11]] <- lmer(log(TEI+1)~group+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[12]] <- lmer(log(TEI+1)~mass.diff+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[13]] <- lmer(log(TEI+1)~mass.diff+temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[14]] <- lmer(log(TEI+1)~temp+bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[15]] <- lmer(log(TEI+1)~temp+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[16]] <- lmer(log(TEI+1)~group+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[17]] <- lmer(log(TEI+1)~mass.diff+(1|id), data=dat, na.action='na.fail',REML = FALSE) 
  candidate_all_TEI[[18]] <- lmer(log(TEI+1)~bout+(1|id), data=dat, na.action='na.fail',REML = FALSE)
  candidate_all_TEI[[19]] <- lmer(log(TEI+1)~1+(1|id), data=dat, na.action='na.fail',REML = FALSE)

candidate_all_TEI_names <- c("Global","Group+Mass+Bout","Temp+Mass+Bout","Temp+Group+Bout","Temp+Group+Mass","Temp+Group+Bout+TempxGroup","Temp+Group+Mass+TempxGroup","Group+Mass","Group+Temp","Group+Temp+TempxGroup","Group+Bout","Mass+Bout","Mass+Temp","Bout+Temp","Temp","Group","Mass","Bout","Null")

all_tei_aic <- aictab(candidate_all_TEI,candidate_all_TEI_names)
all_tei_aic

modavg(candidate_all_TEI,parm='temp23',candidate_all_TEI_names,exclude=list("temp*group"))
summary(candidate_all_TEI[[15]])

```

```{r How is temperature related to performance in Plethodon shermani?}

###These are our Plethodon shermani models exploring how temperature is related to aggressive behavior.

candidate_pshe_TAI <- list()
  candidate_pshe_TAI[[1]] <- lmer(log(TAI+1)~temp+bout+mass.diff+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[2]] <- lmer(log(TAI+1)~temp+bout+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[3]] <- lmer(log(TAI+1)~temp+mass.diff+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[4]] <- lmer(log(TAI+1)~bout+mass.diff+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[5]] <- lmer(log(TAI+1)~temp+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[6]] <- lmer(log(TAI+1)~bout+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[7]] <- lmer(log(TAI+1)~mass.diff+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  candidate_pshe_TAI[[8]] <- lmer(log(TAI+1)~1+(1|id), data=pshe,  na.action='na.fail',REML = FALSE)
  
candidate_pshe_TAI_names <- c("global","temp and bout","temp and mass", "mass and bout", "temp","bout","mass","null")

aictab(candidate_pshe_TAI,candidate_pshe_TAI_names)

modavg(candidate_pshe_TAI, parm='temp23', candidate_pshe_TAI_names)

summary(candidate_pshe_TAI[[5]])



###These are our Plethodon shermani models exploring how temperature is related to evasive behavior.

candidate_pshe_TEI <- list()
  candidate_pshe_TEI[[1]] <- lmer(log(TEI+1)~temp+bout+mass.diff+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[2]] <- lmer(log(TEI+1)~temp+bout+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[3]] <- lmer(log(TEI+1)~temp+mass.diff+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[4]] <- lmer(log(TEI+1)~bout+mass.diff+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[5]] <- lmer(log(TEI+1)~temp+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[6]] <- lmer(log(TEI+1)~bout+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[7]] <- lmer(log(TEI+1)~mass.diff+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  candidate_pshe_TEI[[8]] <- lmer(log(TEI+1)~1+(1|id), data=pshe,  na.action='na.fail',REML=FALSE)
  
candidate_pshe_TEI_names <- c("global","temp and bout","temp and mass", "mass and bout", "temp","bout","mass","null")

aictab(candidate_pshe_TEI,candidate_pshe_TEI_names)

modavg(candidate_pshe_TEI,parm='temp23', candidate_pshe_TEI_names)

summary(candidate_pshe_TEI[[5]])
                           
```

```{r How is temperature related to performance in Plethodon teyahalee?}

###These are our Plethodon teyahalee models exploring how temperature is related to aggressive behavior.

candidate_ptey_TAI <- list()
  candidate_ptey_TAI[[1]] <- lmer(log(TAI+1)~temp+bout+mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[2]] <- lmer(log(TAI+1)~temp+bout+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[3]] <- lmer(log(TAI+1)~temp+mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[4]] <- lmer(log(TAI+1)~bout+mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[5]] <- lmer(log(TAI+1)~temp+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[6]] <- lmer(log(TAI+1)~bout+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[7]] <- lmer(log(TAI+1)~mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TAI[[8]] <- lmer(log(TAI+1)~1+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  
candidate_ptey_TAI_names <- c("global","temp and bout","temp and mass", "mass and bout", "temp","bout","mass","null")

aictab(candidate_ptey_TAI,candidate_ptey_TAI_names)

modavg(candidate_ptey_TAI, parm='temp23', candidate_ptey_TAI_names)

summary(candidate_ptey_TAI[[5]])


###These are our Plethodon teyahalee models exploring how temperature is related to evasive behavior.

candidate_ptey_TEI <- list()
  candidate_ptey_TEI[[1]] <- lmer(log(TEI+1)~temp+bout+mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[2]] <- lmer(log(TEI+1)~temp+bout+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[3]] <- lmer(log(TEI+1)~temp+mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[4]] <- lmer(log(TEI+1)~bout+mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[5]] <- lmer(log(TEI+1)~temp+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[6]] <- lmer(log(TEI+1)~bout+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[7]] <- lmer(log(TEI+1)~mass.diff+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  candidate_ptey_TEI[[8]] <- lmer(log(TEI+1)~1+(1|id), data=ptey,  na.action='na.fail',REML=FALSE)
  
candidate_ptey_TEI_names <- c("global","temp and bout","temp and mass", "mass and bout", "temp","bout","mass","null")

aictab(candidate_ptey_TEI,candidate_ptey_TEI_names)

modavg(candidate_ptey_TEI, parm='temp23', candidate_ptey_TEI_names)

summary(candidate_ptey_TEI[[5]])

```

```{r How is temperature related to performance in hybrids?}
###These are our hybrid models exploring how temperature is related to aggressive behavior.

candidate_pshetey_TAI <- list()
  candidate_pshetey_TAI[[1]] <- lmer(log(TAI+1)~temp+bout+mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[2]] <- lmer(log(TAI+1)~temp+bout+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[3]] <- lmer(log(TAI+1)~temp+mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[4]] <- lmer(log(TAI+1)~bout+mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[5]] <- lmer(log(TAI+1)~temp+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[6]] <- lmer(log(TAI+1)~bout+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[7]] <- lmer(log(TAI+1)~mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TAI[[8]] <- lmer(log(TAI+1)~1+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  
candidate_pshetey_TAI_names <- c("global","temp and bout","temp and mass", "mass and bout", "temp","bout","mass","null")

aictab(candidate_pshetey_TAI,candidate_pshetey_TAI_names)

modavg(candidate_pshetey_TAI, parm='temp23', candidate_pshetey_TAI_names)
summary(candidate_pshetey_TAI[[5]])


###These are our hybrid models exploring how temperature is related to evasive behavior.

candidate_pshetey_TEI <- list()
  candidate_pshetey_TEI[[1]] <- lmer(log(TEI+1)~temp+bout+mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[2]] <- lmer(log(TEI+1)~temp+bout+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[3]] <- lmer(log(TEI+1)~temp+mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[4]] <- lmer(log(TEI+1)~bout+mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[5]] <- lmer(log(TEI+1)~temp+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[6]] <- lmer(log(TEI+1)~bout+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[7]] <- lmer(log(TEI+1)~mass.diff+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  candidate_pshetey_TEI[[8]] <- lmer(log(TEI+1)~1+(1|id), data=pshetey,  na.action='na.fail',REML=FALSE)
  
candidate_pshetey_TEI_names <- c("global","temp and bout","temp and mass", "mass and bout", "temp","bout","mass","null")

aictab(candidate_pshetey_TEI,candidate_pshetey_TEI_names)
#Null model is best, followed by mass (1.40) and temp (1.52)
modavg(candidate_pshetey_TEI, parm='temp23', candidate_pshetey_TEI_names)
summary(candidate_pshetey_TEI[[5]])



```

```{r Population-Split TAI/TEI Figures}

pop.TAI <- ggplot(data=dat,aes(x=pop,y=log(TAI+1),fill=temp))+
  geom_boxplot()+
  scale_fill_manual(values=c("violetred4","orange1"),
      name="Temperature (°C)")+
  geom_point(size=0.75,position=position_jitterdodge(jitter.width=0.2))+ 
  labs(
      y="Total Aggressive Index (TAI)", 
      x="Population")+
      scale_x_discrete(breaks = c("pshe","pshetey","ptey"),
      labels = expression(italic("P. shermani"), "Hybrids", italic("P. teyahalee")))+theme(axis.text=element_text(size=10), axis.title=element_text(size=15),text = element_text(family = "Poppins"),plot.margin=unit(c(2, 1, 1,1),"cm"))

print(pop.TAI)

      

      

pop.TEI <- ggplot(data=dat,aes(x=pop,y=log(TEI+1),fill=temp))+
  geom_boxplot()+
  scale_fill_manual(values=c("darkslategray","olivedrab1"),
      name="Temperature (°C)")+
  geom_point(size=0.75,position=position_jitterdodge(jitter.width=0.2))+
  labs(
      y="Total Evasive Index (TEI)", 
      x="Population")+
  scale_x_discrete(breaks = c("pshe","pshetey","ptey"),
      labels = expression(italic("P. shermani"), "Hybrids", italic("P. teyahalee")))+theme(axis.text=element_text(size=10), axis.title=element_text(size=15),text = element_text(family = "Poppins"),plot.margin=unit(c(2, 1, 1,1),"cm"))

print(pop.TEI)




```

```{r All TAI/TEI Figures}

all.TAI <- ggplot(data=dat,aes(x=temp,y=log(TAI+1),fill=temp))+
  geom_boxplot()+
  scale_fill_manual(values=c("violetred4","orange1"))+
  geom_point(size=0.75,position=position_jitterdodge(jitter.width=0.2))+
  labs( 
      y="Total Aggressive Index (TAI)", 
      x="Temperature (°C)")+
  scale_x_discrete(breaks = c("15","23"),
      labels = c("15", "23"))+
  theme(axis.text=element_text(size=15), axis.title=element_text(size=15),legend.position = "none")+theme(text = element_text(family = "Poppins"),plot.margin=unit(c(1, 1, 1,1),"cm"))
print(all.TAI)

all.TEI <- ggplot(data=dat,aes(x=temp,y=log(TEI+1),fill=temp))+
  geom_boxplot()+
  scale_fill_manual(values=c("darkslategray","olivedrab1"))+
  geom_point(size=0.75,position=position_jitterdodge(jitter.width=0.2))+
  labs( 
      y="Total Evasive Index (TEI)", 
      x="Temperature (°C)")+
  scale_x_discrete(breaks = c("15","23"),
      labels = c("15", "23"))+
  theme(axis.text=element_text(size=15), axis.title=element_text(size=15),legend.position = "none")+theme(text = element_text(family = "Poppins"),plot.margin=unit(c(1, 1, 1,1),"cm"))
print(all.TEI)

```

```{r Initiation Figures}

init.temp <- c("15","15","15","23","23","23")
as.factor(init.temp)
init.spec <- c("pshe","pshetey","ptey","pshe","pshetey","ptey")
init.freq <- c("0.44","0.4","0.36","0.56","0.6","0.29")

init.dat <- data.frame(init.temp,init.spec,init.freq)


initiation.plot <- ggplot(data=init.dat,aes(x=init.spec,y=init.freq, fill=init.temp, group=init.temp))+
  geom_col(position="dodge")+
  scale_fill_manual(values=c("slateblue2","midnightblue"),
      name="Temperature (°C)")+
  labs( 
      y="Proportion of Bouts Initiated", 
      x="Population")+
  scale_x_discrete(breaks = c("pshe","pshetey","ptey"),
      labels = expression(italic("P. shermani"), "Hybrids", italic("P. teyahalee")))+theme(text = element_text(family = "Poppins"))
print(initiation.plot)



```

```{r Performance at Constant Temperature Figure}

tai_at_15 <- ggplot(data=fifteen,aes(x=pop,y=log(TAI+1),fill=pop))+
  geom_boxplot()+theme(legend.position="none")+
  geom_point(position=position_jitterdodge(jitter.width=0.2))+ 
  labs(title="Aggression at a Constant Temperature",
      subtitle="TAI of Different Populations at 15°C", 
      y="Total Aggressive Index (TAI)", 
      x="Population")+
  scale_fill_manual(values=c("thistle1","plum3","plum4"))+
  scale_x_discrete(breaks = c("pshe","pshetey","ptey"),
      labels = expression(italic("P. shermani"), "Hybrids", italic("P. teyahalee")))+theme(text = element_text(family = "Poppins"))

tai_at_15

tei_at_15 <- ggplot(data=fifteen,aes(x=pop,y=log(TEI+1),fill=pop))+
  geom_boxplot()+theme(legend.position="none")+
  geom_point(position=position_jitterdodge(jitter.width=0.2))+ 
  labs(title="Evasion at a Constant Temperature",
      subtitle="TEI of Different Populations at 15°C", 
      y="Total Evasive Index (TEI)", 
      x="Population")+
    scale_fill_manual(values=c("thistle1","plum3","plum4"))+
  scale_x_discrete(breaks = c("pshe","pshetey","ptey"),
      labels = expression(italic("P. shermani"), "Hybrids", italic("P. teyahalee")))+theme(text = element_text(family = "Poppins"))

tei_at_15

```

```{r Tables}
# saving the candidate singular models as their own call
TAI_temp_model <- candidate_all_TAI[[15]]
TEI_temp_model <- candidate_all_TEI[[15]]
TAI_temp_pshe <- candidate_pshe_TAI[[5]]
TEI_temp_pshe <- candidate_pshe_TEI[[5]]
TAI_temp_ptey <- candidate_ptey_TAI[[5]]
TEI_temp_ptey <- candidate_ptey_TEI[[5]]
TAI_temp_pshetey <- candidate_pshetey_TAI[[5]]
TEI_temp_pshetey <- candidate_pshetey_TEI[[5]]

# summarizing the single models and saving those
TAI_temp_model_summary <- summary(TAI_temp_model)
TEI_temp_model_summary <- summary(TEI_temp_model)
TAI_temp_pshe_summary <- summary(TAI_temp_pshe)
TEI_temp_pshe_summary <- summary(TEI_temp_pshe)
TAI_temp_ptey_summary <- summary(TAI_temp_ptey)
TEI_temp_ptey_summary <- summary(TEI_temp_ptey)
TAI_temp_pshetey_summary <- summary(TAI_temp_pshetey)
TEI_temp_pshetey_summary <- summary(TEI_temp_pshetey)


# Making the results for TAI
TAI_all_results <- c("TAI", "Temp","All",
                 TAI_temp_model_summary$coefficients[2,1],
                 TAI_temp_model_summary$coefficients[2,2],
                 TAI_temp_model_summary$coefficients[2,3],
                 TAI_temp_model_summary$coefficients[2,4],
                 TAI_temp_model_summary$coefficients[2,5])
TAI_pshe_results <- c("TAI", "Temp","P.shermani",
                 TAI_temp_pshe_summary$coefficients[2,1],
                 TAI_temp_pshe_summary$coefficients[2,2],
                 TAI_temp_pshe_summary$coefficients[2,3],
                 TAI_temp_pshe_summary$coefficients[2,4],
                 TAI_temp_pshe_summary$coefficients[2,5])
TAI_ptey_results <- c("TAI", "Temp","P.teyahalee",
                 TAI_temp_ptey_summary$coefficients[2,1],
                 TAI_temp_ptey_summary$coefficients[2,2],
                 TAI_temp_ptey_summary$coefficients[2,3],
                 TAI_temp_ptey_summary$coefficients[2,4],
                 TAI_temp_ptey_summary$coefficients[2,5])
TAI_pshetey_results <- c("TAI", "Temp","Hybrids",
                 TAI_temp_pshetey_summary$coefficients[2,1],
                 TAI_temp_pshetey_summary$coefficients[2,2],
                 TAI_temp_pshetey_summary$coefficients[2,3],
                 TAI_temp_pshetey_summary$coefficients[2,4],
                 TAI_temp_pshetey_summary$coefficients[2,5])


# Making the results for TEI
TEI_all_results <- c("TEI", "Temp","All",
                 TEI_temp_model_summary$coefficients[2,1],
                 TEI_temp_model_summary$coefficients[2,2],
                 TEI_temp_model_summary$coefficients[2,3],
                 TEI_temp_model_summary$coefficients[2,4],
                 TEI_temp_model_summary$coefficients[2,5])
TEI_pshe_results <- c("TEI", "Temp","P.shermani",
                 TEI_temp_pshe_summary$coefficients[2,1],
                 TEI_temp_pshe_summary$coefficients[2,2],
                 TEI_temp_pshe_summary$coefficients[2,3],
                 TEI_temp_pshe_summary$coefficients[2,4],
                 TEI_temp_pshe_summary$coefficients[2,5])
TEI_ptey_results <- c("TEI", "Temp","P.teyahalee",
                 TEI_temp_ptey_summary$coefficients[2,1],
                 TEI_temp_ptey_summary$coefficients[2,2],
                 TEI_temp_ptey_summary$coefficients[2,3],
                 TEI_temp_ptey_summary$coefficients[2,4],
                 TEI_temp_ptey_summary$coefficients[2,5])
TEI_pshetey_results <- c("TEI", "Temp","Hybrids",
                 TEI_temp_pshetey_summary$coefficients[2,1],
                 TEI_temp_pshetey_summary$coefficients[2,2],
                 TEI_temp_pshetey_summary$coefficients[2,3],
                 TEI_temp_pshetey_summary$coefficients[2,4],
                 TEI_temp_pshetey_summary$coefficients[2,5])

# Turning tables into dataframes
TAI_all_results <- as.data.frame(t(TAI_all_results))
TEI_all_results <- as.data.frame(t(TEI_all_results))
TAI_pshe_results <- as.data.frame(t(TAI_pshe_results))
TEI_pshe_results <- as.data.frame(t(TEI_pshe_results))
TAI_ptey_results <- as.data.frame(t(TAI_ptey_results))
TEI_ptey_results <- as.data.frame(t(TEI_ptey_results))
TAI_pshetey_results <- as.data.frame(t(TAI_pshetey_results))
TEI_pshetey_results <- as.data.frame(t(TEI_pshetey_results))




# Converting to numeric
TAI_all_results[4:8] <- lapply(TAI_all_results[4:8],as.numeric)
TEI_all_results[4:8] <- lapply(TEI_all_results[4:8],as.numeric)
TAI_pshe_results[4:8] <- lapply(TAI_pshe_results[4:8],as.numeric)
TEI_pshe_results[4:8] <- lapply(TEI_pshe_results[4:8],as.numeric)
TAI_ptey_results[4:8] <- lapply(TAI_ptey_results[4:8],as.numeric)
TEI_ptey_results[4:8] <- lapply(TEI_ptey_results[4:8],as.numeric)
TAI_pshetey_results[4:8] <- lapply(TAI_pshetey_results[4:8],as.numeric)
TEI_pshetey_results[4:8] <- lapply(TEI_pshetey_results[4:8],as.numeric)


# binding the rows together
Full_results <- rbind(TAI_all_results, TEI_all_results, TAI_pshe_results, TEI_pshe_results, TAI_ptey_results, TEI_ptey_results, TAI_pshetey_results, TEI_pshetey_results)

library(dplyr)
library(kableExtra)
# naming the columns with the columns of interest
Results_header <- c("Response", "Predictor","Population", "Model Est", "Model SE", "DF", "t-value", "P-value")
colnames(Full_results) <- Results_header

# rounding to 2 digits
Full_results <- Full_results %>% mutate_if(is.numeric, round, digits = 2)
Full_results %>% select(-c("Predictor"))%>%kbl() %>% kable_classic(html_font = "Cambria", font_size=40)

# Making a nice table!!!
Full_results %>%kbl() %>% kable_classic(html_font = "Cambria", font_size=20)

# Making table showing the individual models used for the averaging
# c(1,4) is simply just pulling the first and fourth columns. row.names = FALSE to get rid  of the numbers, col.names to rename the columns, digits = numbers
all_tai_aic[,c(1,3:8)] %>% kbl(row.names = FALSE,
                             col.names = c("Predictor Variables", "AICC", "Delta AICc","Model Likelihood", "AICc Weight", "Log Likelihood", "Cumulative Weight"),
                             digits = 2) %>% kable_classic(html_font = "Cambria")
all_tei_aic[,c(1,3:8)] %>% kbl(row.names = FALSE,
                             col.names = c("Predictor Variables", "AICC", "Delta AICc","Model Likelihood", "AICc Weight", "Log Likelihood", "Cumulative Weight"),
                             digits = 2) %>% kable_classic(html_font = "Cambria")






```
```{r More tables}

# saving the average models
TAI_modavg <- modavg(candidate_all_TAI,parm='temp23',candidate_all_TAI_names,exclude=list("temp*group"))
TEI_modavg <- modavg(candidate_all_TEI,parm='temp23',candidate_all_TEI_names,exclude=list("temp*group"))
TAI_sher_avg <- modavg(candidate_pshe_TAI, parm='temp23', candidate_pshe_TAI_names)
TEI_sher_avg <- modavg(candidate_pshe_TEI, parm='temp23', candidate_pshe_TEI_names)
TAI_tey_avg <- modavg(candidate_ptey_TAI, parm='temp23', candidate_ptey_TAI_names)
TEI_tey_avg <- modavg(candidate_ptey_TEI, parm='temp23', candidate_ptey_TEI_names)
TAI_hyb_avg <- modavg(candidate_pshetey_TAI, parm='temp23', candidate_pshetey_TAI_names)
TEI_hyb_avg <- modavg(candidate_pshetey_TEI, parm='temp23', candidate_pshetey_TEI_names)



# Making the results for TAI
TAI_tempavg <- c("TAI","All",
                 TAI_modavg$Mod.avg.beta,
                 TAI_modavg$Uncond.SE,
                 TAI_modavg$Conf.level,
                 TAI_modavg$Lower.CL,
                 TAI_modavg$Upper.CL)

# Making the results for TEI
TEI_tempavg <- c("TEI","All",
                 TEI_modavg$Mod.avg.beta,
                 TEI_modavg$Uncond.SE,
                 TEI_modavg$Conf.level,
                 TEI_modavg$Lower.CL,
                 TEI_modavg$Upper.CL)

TAI_sher_tempavg <- c("TAI","P.shermani",
                 TAI_sher_avg$Mod.avg.beta,
                 TAI_sher_avg$Uncond.SE,
                 TAI_sher_avg$Conf.level,
                 TAI_sher_avg$Lower.CL,
                 TAI_sher_avg$Upper.CL)
TEI_sher_tempavg <- c("TEI","P.shermani",
                 TEI_sher_avg$Mod.avg.beta,
                 TEI_sher_avg$Uncond.SE,
                 TEI_sher_avg$Conf.level,
                 TEI_sher_avg$Lower.CL,
                 TEI_sher_avg$Upper.CL)
TAI_tey_tempavg <- c("TAI","P.teyahalee",
                 TAI_tey_avg$Mod.avg.beta,
                 TAI_tey_avg$Uncond.SE,
                 TAI_tey_avg$Conf.level,
                 TAI_tey_avg$Lower.CL,
                 TAI_tey_avg$Upper.CL)
TEI_tey_tempavg <- c("TEI","P.teyahalee",
                 TEI_tey_avg$Mod.avg.beta,
                 TEI_tey_avg$Uncond.SE,
                 TEI_tey_avg$Conf.level,
                 TEI_tey_avg$Lower.CL,
                 TEI_tey_avg$Upper.CL)
TAI_hyb_tempavg <- c("TAI","Hybrids",
                 TAI_hyb_avg$Mod.avg.beta,
                 TAI_hyb_avg$Uncond.SE,
                 TAI_hyb_avg$Conf.level,
                 TAI_hyb_avg$Lower.CL,
                 TAI_hyb_avg$Upper.CL)
TEI_hyb_tempavg <- c("TEI","Hybrids",
                 TEI_hyb_avg$Mod.avg.beta,
                 TEI_hyb_avg$Uncond.SE,
                 TEI_hyb_avg$Conf.level,
                 TEI_hyb_avg$Lower.CL,
                 TEI_hyb_avg$Upper.CL)


# Turning tables into dataframes
TAI_tempavg <- as.data.frame(t(TAI_tempavg))
TEI_tempavg <- as.data.frame(t(TEI_tempavg))
TAI_sher_tempavg <- as.data.frame(t(TAI_sher_tempavg))
TEI_sher_tempavg <- as.data.frame(t(TEI_sher_tempavg))
TAI_tey_tempavg <- as.data.frame(t(TAI_tey_tempavg))
TEI_tey_tempavg <- as.data.frame(t(TEI_tey_tempavg))
TAI_hyb_tempavg <- as.data.frame(t(TAI_hyb_tempavg))
TEI_hyb_tempavg <- as.data.frame(t(TEI_hyb_tempavg))


# Converting to numeric
TAI_tempavg[3:7] <- lapply(TAI_tempavg[3:7],as.numeric)
TEI_tempavg[3:7] <- lapply(TEI_tempavg[3:7],as.numeric)
TAI_sher_tempavg[3:7] <- lapply(TAI_sher_tempavg[3:7],as.numeric)
TEI_sher_tempavg[3:7] <- lapply(TEI_sher_tempavg[3:7],as.numeric)
TAI_tey_tempavg[3:7] <- lapply(TAI_tey_tempavg[3:7],as.numeric)
TEI_tey_tempavg[3:7] <- lapply(TEI_tey_tempavg[3:7],as.numeric)
TAI_hyb_tempavg[3:7] <- lapply(TAI_hyb_tempavg[3:7],as.numeric)
TEI_hyb_tempavg[3:7] <- lapply(TEI_hyb_tempavg[3:7],as.numeric)


# binding the rows together
Avg_results <- rbind(TAI_tempavg, TEI_tempavg,TAI_sher_tempavg,TEI_sher_tempavg,TAI_tey_tempavg,TEI_tey_tempavg,TAI_hyb_tempavg,TEI_hyb_tempavg)

# naming the columns with the columns of interest
Results_header <- c("Response", "Population", "Model-Averaged Estimate", "Model-Averaged SE", "Confidence Level", "Lower CI", "Upper CI")
colnames(Avg_results) <- Results_header

# rounding to 2 digits
Avg_results <- Avg_results %>% mutate_if(is.numeric, round, digits = 2)
Avg_results


# Making a nice table!!!
Avg_results %>%kbl() %>% kable_classic(html_font = "Cambria",font_size=40)


```





